### ISSUE TITLE
Items within Array.map() are not getting updated as table rows

### ISSUE THREAD

**Issue by supminn** [supminn/neoG_CashRegManager#3]
### Kindly refer to app.js within supminn-styles branch.
I am trying to populate the change as a table. However the <tbody> is **not getting populated** with the data iterated through map()

![image](https://user-images.githubusercontent.com/30731236/103220597-a2097800-4946-11eb-94f9-ba4745052cda.png)

### I am able to view this on inspecting

![image](https://user-images.githubusercontent.com/30731236/103220642-c82f1800-4946-11eb-90d8-ce9dd10fe813.png)

**Comment by akshay-rajput** [comment]
It looks like you are displaying values inside b tag, instead of <tr> tag.
